/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* TRACE_POSTGRESQL_TRANSACTION_START ( unsigned int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_TRANSACTION_START_ENABLED() __builtin_expect (transaction__start_semaphore, 0)
#define postgresql_transaction__start_semaphore transaction__start_semaphore
#else
#define TRACE_POSTGRESQL_TRANSACTION_START_ENABLED() __builtin_expect (postgresql_transaction__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_transaction__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_TRANSACTION_START(arg1) \
DTRACE_PROBE1 (postgresql, transaction__start, arg1)

/* TRACE_POSTGRESQL_TRANSACTION_COMMIT ( unsigned int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_TRANSACTION_COMMIT_ENABLED() __builtin_expect (transaction__commit_semaphore, 0)
#define postgresql_transaction__commit_semaphore transaction__commit_semaphore
#else
#define TRACE_POSTGRESQL_TRANSACTION_COMMIT_ENABLED() __builtin_expect (postgresql_transaction__commit_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_transaction__commit_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_TRANSACTION_COMMIT(arg1) \
DTRACE_PROBE1 (postgresql, transaction__commit, arg1)

/* TRACE_POSTGRESQL_TRANSACTION_ABORT ( unsigned int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_TRANSACTION_ABORT_ENABLED() __builtin_expect (transaction__abort_semaphore, 0)
#define postgresql_transaction__abort_semaphore transaction__abort_semaphore
#else
#define TRACE_POSTGRESQL_TRANSACTION_ABORT_ENABLED() __builtin_expect (postgresql_transaction__abort_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_transaction__abort_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_TRANSACTION_ABORT(arg1) \
DTRACE_PROBE1 (postgresql, transaction__abort, arg1)

/* TRACE_POSTGRESQL_LWLOCK_ACQUIRE ( const char *, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_ENABLED() __builtin_expect (lwlock__acquire_semaphore, 0)
#define postgresql_lwlock__acquire_semaphore lwlock__acquire_semaphore
#else
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_ENABLED() __builtin_expect (postgresql_lwlock__acquire_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_lwlock__acquire_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE(arg1, arg2) \
DTRACE_PROBE2 (postgresql, lwlock__acquire, arg1, arg2)

/* TRACE_POSTGRESQL_LWLOCK_RELEASE ( const char * ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_LWLOCK_RELEASE_ENABLED() __builtin_expect (lwlock__release_semaphore, 0)
#define postgresql_lwlock__release_semaphore lwlock__release_semaphore
#else
#define TRACE_POSTGRESQL_LWLOCK_RELEASE_ENABLED() __builtin_expect (postgresql_lwlock__release_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_lwlock__release_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_LWLOCK_RELEASE(arg1) \
DTRACE_PROBE1 (postgresql, lwlock__release, arg1)

/* TRACE_POSTGRESQL_LWLOCK_WAIT_START ( const char *, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_LWLOCK_WAIT_START_ENABLED() __builtin_expect (lwlock__wait__start_semaphore, 0)
#define postgresql_lwlock__wait__start_semaphore lwlock__wait__start_semaphore
#else
#define TRACE_POSTGRESQL_LWLOCK_WAIT_START_ENABLED() __builtin_expect (postgresql_lwlock__wait__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_lwlock__wait__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_LWLOCK_WAIT_START(arg1, arg2) \
DTRACE_PROBE2 (postgresql, lwlock__wait__start, arg1, arg2)

/* TRACE_POSTGRESQL_LWLOCK_WAIT_DONE ( const char *, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_LWLOCK_WAIT_DONE_ENABLED() __builtin_expect (lwlock__wait__done_semaphore, 0)
#define postgresql_lwlock__wait__done_semaphore lwlock__wait__done_semaphore
#else
#define TRACE_POSTGRESQL_LWLOCK_WAIT_DONE_ENABLED() __builtin_expect (postgresql_lwlock__wait__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_lwlock__wait__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_LWLOCK_WAIT_DONE(arg1, arg2) \
DTRACE_PROBE2 (postgresql, lwlock__wait__done, arg1, arg2)

/* TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE ( const char *, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_ENABLED() __builtin_expect (lwlock__condacquire_semaphore, 0)
#define postgresql_lwlock__condacquire_semaphore lwlock__condacquire_semaphore
#else
#define TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_ENABLED() __builtin_expect (postgresql_lwlock__condacquire_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_lwlock__condacquire_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE(arg1, arg2) \
DTRACE_PROBE2 (postgresql, lwlock__condacquire, arg1, arg2)

/* TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_FAIL ( const char *, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_FAIL_ENABLED() __builtin_expect (lwlock__condacquire__fail_semaphore, 0)
#define postgresql_lwlock__condacquire__fail_semaphore lwlock__condacquire__fail_semaphore
#else
#define TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_FAIL_ENABLED() __builtin_expect (postgresql_lwlock__condacquire__fail_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_lwlock__condacquire__fail_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_FAIL(arg1, arg2) \
DTRACE_PROBE2 (postgresql, lwlock__condacquire__fail, arg1, arg2)

/* TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT ( const char *, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT_ENABLED() __builtin_expect (lwlock__acquire__or__wait_semaphore, 0)
#define postgresql_lwlock__acquire__or__wait_semaphore lwlock__acquire__or__wait_semaphore
#else
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT_ENABLED() __builtin_expect (postgresql_lwlock__acquire__or__wait_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_lwlock__acquire__or__wait_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT(arg1, arg2) \
DTRACE_PROBE2 (postgresql, lwlock__acquire__or__wait, arg1, arg2)

/* TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT_FAIL ( const char *, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT_FAIL_ENABLED() __builtin_expect (lwlock__acquire__or__wait__fail_semaphore, 0)
#define postgresql_lwlock__acquire__or__wait__fail_semaphore lwlock__acquire__or__wait__fail_semaphore
#else
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT_FAIL_ENABLED() __builtin_expect (postgresql_lwlock__acquire__or__wait__fail_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_lwlock__acquire__or__wait__fail_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT_FAIL(arg1, arg2) \
DTRACE_PROBE2 (postgresql, lwlock__acquire__or__wait__fail, arg1, arg2)

/* TRACE_POSTGRESQL_LOCK_WAIT_START ( unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_LOCK_WAIT_START_ENABLED() __builtin_expect (lock__wait__start_semaphore, 0)
#define postgresql_lock__wait__start_semaphore lock__wait__start_semaphore
#else
#define TRACE_POSTGRESQL_LOCK_WAIT_START_ENABLED() __builtin_expect (postgresql_lock__wait__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_lock__wait__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_LOCK_WAIT_START(arg1, arg2, arg3, arg4, arg5, arg6) \
DTRACE_PROBE6 (postgresql, lock__wait__start, arg1, arg2, arg3, arg4, arg5, arg6)

/* TRACE_POSTGRESQL_LOCK_WAIT_DONE ( unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_LOCK_WAIT_DONE_ENABLED() __builtin_expect (lock__wait__done_semaphore, 0)
#define postgresql_lock__wait__done_semaphore lock__wait__done_semaphore
#else
#define TRACE_POSTGRESQL_LOCK_WAIT_DONE_ENABLED() __builtin_expect (postgresql_lock__wait__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_lock__wait__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_LOCK_WAIT_DONE(arg1, arg2, arg3, arg4, arg5, arg6) \
DTRACE_PROBE6 (postgresql, lock__wait__done, arg1, arg2, arg3, arg4, arg5, arg6)

/* TRACE_POSTGRESQL_QUERY_PARSE_START ( const char * ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_QUERY_PARSE_START_ENABLED() __builtin_expect (query__parse__start_semaphore, 0)
#define postgresql_query__parse__start_semaphore query__parse__start_semaphore
#else
#define TRACE_POSTGRESQL_QUERY_PARSE_START_ENABLED() __builtin_expect (postgresql_query__parse__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_query__parse__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_QUERY_PARSE_START(arg1) \
DTRACE_PROBE1 (postgresql, query__parse__start, arg1)

/* TRACE_POSTGRESQL_QUERY_PARSE_DONE ( const char * ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_QUERY_PARSE_DONE_ENABLED() __builtin_expect (query__parse__done_semaphore, 0)
#define postgresql_query__parse__done_semaphore query__parse__done_semaphore
#else
#define TRACE_POSTGRESQL_QUERY_PARSE_DONE_ENABLED() __builtin_expect (postgresql_query__parse__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_query__parse__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_QUERY_PARSE_DONE(arg1) \
DTRACE_PROBE1 (postgresql, query__parse__done, arg1)

/* TRACE_POSTGRESQL_QUERY_REWRITE_START ( const char * ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_QUERY_REWRITE_START_ENABLED() __builtin_expect (query__rewrite__start_semaphore, 0)
#define postgresql_query__rewrite__start_semaphore query__rewrite__start_semaphore
#else
#define TRACE_POSTGRESQL_QUERY_REWRITE_START_ENABLED() __builtin_expect (postgresql_query__rewrite__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_query__rewrite__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_QUERY_REWRITE_START(arg1) \
DTRACE_PROBE1 (postgresql, query__rewrite__start, arg1)

/* TRACE_POSTGRESQL_QUERY_REWRITE_DONE ( const char * ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_QUERY_REWRITE_DONE_ENABLED() __builtin_expect (query__rewrite__done_semaphore, 0)
#define postgresql_query__rewrite__done_semaphore query__rewrite__done_semaphore
#else
#define TRACE_POSTGRESQL_QUERY_REWRITE_DONE_ENABLED() __builtin_expect (postgresql_query__rewrite__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_query__rewrite__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_QUERY_REWRITE_DONE(arg1) \
DTRACE_PROBE1 (postgresql, query__rewrite__done, arg1)

/* TRACE_POSTGRESQL_QUERY_PLAN_START ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_QUERY_PLAN_START_ENABLED() __builtin_expect (query__plan__start_semaphore, 0)
#define postgresql_query__plan__start_semaphore query__plan__start_semaphore
#else
#define TRACE_POSTGRESQL_QUERY_PLAN_START_ENABLED() __builtin_expect (postgresql_query__plan__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_query__plan__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_QUERY_PLAN_START() \
DTRACE_PROBE (postgresql, query__plan__start)

/* TRACE_POSTGRESQL_QUERY_PLAN_DONE ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_QUERY_PLAN_DONE_ENABLED() __builtin_expect (query__plan__done_semaphore, 0)
#define postgresql_query__plan__done_semaphore query__plan__done_semaphore
#else
#define TRACE_POSTGRESQL_QUERY_PLAN_DONE_ENABLED() __builtin_expect (postgresql_query__plan__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_query__plan__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_QUERY_PLAN_DONE() \
DTRACE_PROBE (postgresql, query__plan__done)

/* TRACE_POSTGRESQL_QUERY_EXECUTE_START ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_QUERY_EXECUTE_START_ENABLED() __builtin_expect (query__execute__start_semaphore, 0)
#define postgresql_query__execute__start_semaphore query__execute__start_semaphore
#else
#define TRACE_POSTGRESQL_QUERY_EXECUTE_START_ENABLED() __builtin_expect (postgresql_query__execute__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_query__execute__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_QUERY_EXECUTE_START() \
DTRACE_PROBE (postgresql, query__execute__start)

/* TRACE_POSTGRESQL_QUERY_EXECUTE_DONE ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_QUERY_EXECUTE_DONE_ENABLED() __builtin_expect (query__execute__done_semaphore, 0)
#define postgresql_query__execute__done_semaphore query__execute__done_semaphore
#else
#define TRACE_POSTGRESQL_QUERY_EXECUTE_DONE_ENABLED() __builtin_expect (postgresql_query__execute__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_query__execute__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_QUERY_EXECUTE_DONE() \
DTRACE_PROBE (postgresql, query__execute__done)

/* TRACE_POSTGRESQL_QUERY_START ( const char * ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_QUERY_START_ENABLED() __builtin_expect (query__start_semaphore, 0)
#define postgresql_query__start_semaphore query__start_semaphore
#else
#define TRACE_POSTGRESQL_QUERY_START_ENABLED() __builtin_expect (postgresql_query__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_query__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_QUERY_START(arg1) \
DTRACE_PROBE1 (postgresql, query__start, arg1)

/* TRACE_POSTGRESQL_QUERY_DONE ( const char * ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_QUERY_DONE_ENABLED() __builtin_expect (query__done_semaphore, 0)
#define postgresql_query__done_semaphore query__done_semaphore
#else
#define TRACE_POSTGRESQL_QUERY_DONE_ENABLED() __builtin_expect (postgresql_query__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_query__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_QUERY_DONE(arg1) \
DTRACE_PROBE1 (postgresql, query__done, arg1)

/* TRACE_POSTGRESQL_STATEMENT_STATUS ( const char * ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_STATEMENT_STATUS_ENABLED() __builtin_expect (statement__status_semaphore, 0)
#define postgresql_statement__status_semaphore statement__status_semaphore
#else
#define TRACE_POSTGRESQL_STATEMENT_STATUS_ENABLED() __builtin_expect (postgresql_statement__status_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_statement__status_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_STATEMENT_STATUS(arg1) \
DTRACE_PROBE1 (postgresql, statement__status, arg1)

/* TRACE_POSTGRESQL_SORT_START ( int, char, int, int, char, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_SORT_START_ENABLED() __builtin_expect (sort__start_semaphore, 0)
#define postgresql_sort__start_semaphore sort__start_semaphore
#else
#define TRACE_POSTGRESQL_SORT_START_ENABLED() __builtin_expect (postgresql_sort__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_sort__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_SORT_START(arg1, arg2, arg3, arg4, arg5, arg6) \
DTRACE_PROBE6 (postgresql, sort__start, arg1, arg2, arg3, arg4, arg5, arg6)

/* TRACE_POSTGRESQL_SORT_DONE ( char, long ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_SORT_DONE_ENABLED() __builtin_expect (sort__done_semaphore, 0)
#define postgresql_sort__done_semaphore sort__done_semaphore
#else
#define TRACE_POSTGRESQL_SORT_DONE_ENABLED() __builtin_expect (postgresql_sort__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_sort__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_SORT_DONE(arg1, arg2) \
DTRACE_PROBE2 (postgresql, sort__done, arg1, arg2)

/* TRACE_POSTGRESQL_BUFFER_READ_START ( int, unsigned int, unsigned int, unsigned int, unsigned int, int, char ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_READ_START_ENABLED() __builtin_expect (buffer__read__start_semaphore, 0)
#define postgresql_buffer__read__start_semaphore buffer__read__start_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_READ_START_ENABLED() __builtin_expect (postgresql_buffer__read__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__read__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_READ_START(arg1, arg2, arg3, arg4, arg5, arg6, arg7) \
DTRACE_PROBE7 (postgresql, buffer__read__start, arg1, arg2, arg3, arg4, arg5, arg6, arg7)

/* TRACE_POSTGRESQL_BUFFER_READ_DONE ( int, unsigned int, unsigned int, unsigned int, unsigned int, int, char, char ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_READ_DONE_ENABLED() __builtin_expect (buffer__read__done_semaphore, 0)
#define postgresql_buffer__read__done_semaphore buffer__read__done_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_READ_DONE_ENABLED() __builtin_expect (postgresql_buffer__read__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__read__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_READ_DONE(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) \
DTRACE_PROBE8 (postgresql, buffer__read__done, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)

/* TRACE_POSTGRESQL_BUFFER_FLUSH_START ( int, unsigned int, unsigned int, unsigned int, unsigned int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_FLUSH_START_ENABLED() __builtin_expect (buffer__flush__start_semaphore, 0)
#define postgresql_buffer__flush__start_semaphore buffer__flush__start_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_FLUSH_START_ENABLED() __builtin_expect (postgresql_buffer__flush__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__flush__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_FLUSH_START(arg1, arg2, arg3, arg4, arg5) \
DTRACE_PROBE5 (postgresql, buffer__flush__start, arg1, arg2, arg3, arg4, arg5)

/* TRACE_POSTGRESQL_BUFFER_FLUSH_DONE ( int, unsigned int, unsigned int, unsigned int, unsigned int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_FLUSH_DONE_ENABLED() __builtin_expect (buffer__flush__done_semaphore, 0)
#define postgresql_buffer__flush__done_semaphore buffer__flush__done_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_FLUSH_DONE_ENABLED() __builtin_expect (postgresql_buffer__flush__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__flush__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_FLUSH_DONE(arg1, arg2, arg3, arg4, arg5) \
DTRACE_PROBE5 (postgresql, buffer__flush__done, arg1, arg2, arg3, arg4, arg5)

/* TRACE_POSTGRESQL_BUFFER_CHECKPOINT_START ( int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_START_ENABLED() __builtin_expect (buffer__checkpoint__start_semaphore, 0)
#define postgresql_buffer__checkpoint__start_semaphore buffer__checkpoint__start_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_START_ENABLED() __builtin_expect (postgresql_buffer__checkpoint__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__checkpoint__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_START(arg1) \
DTRACE_PROBE1 (postgresql, buffer__checkpoint__start, arg1)

/* TRACE_POSTGRESQL_BUFFER_CHECKPOINT_SYNC_START ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_SYNC_START_ENABLED() __builtin_expect (buffer__checkpoint__sync__start_semaphore, 0)
#define postgresql_buffer__checkpoint__sync__start_semaphore buffer__checkpoint__sync__start_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_SYNC_START_ENABLED() __builtin_expect (postgresql_buffer__checkpoint__sync__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__checkpoint__sync__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_SYNC_START() \
DTRACE_PROBE (postgresql, buffer__checkpoint__sync__start)

/* TRACE_POSTGRESQL_BUFFER_CHECKPOINT_DONE ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_DONE_ENABLED() __builtin_expect (buffer__checkpoint__done_semaphore, 0)
#define postgresql_buffer__checkpoint__done_semaphore buffer__checkpoint__done_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_DONE_ENABLED() __builtin_expect (postgresql_buffer__checkpoint__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__checkpoint__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_DONE() \
DTRACE_PROBE (postgresql, buffer__checkpoint__done)

/* TRACE_POSTGRESQL_BUFFER_SYNC_START ( int, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_SYNC_START_ENABLED() __builtin_expect (buffer__sync__start_semaphore, 0)
#define postgresql_buffer__sync__start_semaphore buffer__sync__start_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_SYNC_START_ENABLED() __builtin_expect (postgresql_buffer__sync__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__sync__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_SYNC_START(arg1, arg2) \
DTRACE_PROBE2 (postgresql, buffer__sync__start, arg1, arg2)

/* TRACE_POSTGRESQL_BUFFER_SYNC_WRITTEN ( int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_SYNC_WRITTEN_ENABLED() __builtin_expect (buffer__sync__written_semaphore, 0)
#define postgresql_buffer__sync__written_semaphore buffer__sync__written_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_SYNC_WRITTEN_ENABLED() __builtin_expect (postgresql_buffer__sync__written_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__sync__written_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_SYNC_WRITTEN(arg1) \
DTRACE_PROBE1 (postgresql, buffer__sync__written, arg1)

/* TRACE_POSTGRESQL_BUFFER_SYNC_DONE ( int, int, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_SYNC_DONE_ENABLED() __builtin_expect (buffer__sync__done_semaphore, 0)
#define postgresql_buffer__sync__done_semaphore buffer__sync__done_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_SYNC_DONE_ENABLED() __builtin_expect (postgresql_buffer__sync__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__sync__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_SYNC_DONE(arg1, arg2, arg3) \
DTRACE_PROBE3 (postgresql, buffer__sync__done, arg1, arg2, arg3)

/* TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_START ( int, unsigned int, unsigned int, unsigned int, unsigned int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_START_ENABLED() __builtin_expect (buffer__write__dirty__start_semaphore, 0)
#define postgresql_buffer__write__dirty__start_semaphore buffer__write__dirty__start_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_START_ENABLED() __builtin_expect (postgresql_buffer__write__dirty__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__write__dirty__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_START(arg1, arg2, arg3, arg4, arg5) \
DTRACE_PROBE5 (postgresql, buffer__write__dirty__start, arg1, arg2, arg3, arg4, arg5)

/* TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_DONE ( int, unsigned int, unsigned int, unsigned int, unsigned int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_DONE_ENABLED() __builtin_expect (buffer__write__dirty__done_semaphore, 0)
#define postgresql_buffer__write__dirty__done_semaphore buffer__write__dirty__done_semaphore
#else
#define TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_DONE_ENABLED() __builtin_expect (postgresql_buffer__write__dirty__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_buffer__write__dirty__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_DONE(arg1, arg2, arg3, arg4, arg5) \
DTRACE_PROBE5 (postgresql, buffer__write__dirty__done, arg1, arg2, arg3, arg4, arg5)

/* TRACE_POSTGRESQL_DEADLOCK_FOUND ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_DEADLOCK_FOUND_ENABLED() __builtin_expect (deadlock__found_semaphore, 0)
#define postgresql_deadlock__found_semaphore deadlock__found_semaphore
#else
#define TRACE_POSTGRESQL_DEADLOCK_FOUND_ENABLED() __builtin_expect (postgresql_deadlock__found_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_deadlock__found_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_DEADLOCK_FOUND() \
DTRACE_PROBE (postgresql, deadlock__found)

/* TRACE_POSTGRESQL_CHECKPOINT_START ( int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_CHECKPOINT_START_ENABLED() __builtin_expect (checkpoint__start_semaphore, 0)
#define postgresql_checkpoint__start_semaphore checkpoint__start_semaphore
#else
#define TRACE_POSTGRESQL_CHECKPOINT_START_ENABLED() __builtin_expect (postgresql_checkpoint__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_checkpoint__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_CHECKPOINT_START(arg1) \
DTRACE_PROBE1 (postgresql, checkpoint__start, arg1)

/* TRACE_POSTGRESQL_CHECKPOINT_DONE ( int, int, int, int, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_CHECKPOINT_DONE_ENABLED() __builtin_expect (checkpoint__done_semaphore, 0)
#define postgresql_checkpoint__done_semaphore checkpoint__done_semaphore
#else
#define TRACE_POSTGRESQL_CHECKPOINT_DONE_ENABLED() __builtin_expect (postgresql_checkpoint__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_checkpoint__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_CHECKPOINT_DONE(arg1, arg2, arg3, arg4, arg5) \
DTRACE_PROBE5 (postgresql, checkpoint__done, arg1, arg2, arg3, arg4, arg5)

/* TRACE_POSTGRESQL_CLOG_CHECKPOINT_START ( char ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_CLOG_CHECKPOINT_START_ENABLED() __builtin_expect (clog__checkpoint__start_semaphore, 0)
#define postgresql_clog__checkpoint__start_semaphore clog__checkpoint__start_semaphore
#else
#define TRACE_POSTGRESQL_CLOG_CHECKPOINT_START_ENABLED() __builtin_expect (postgresql_clog__checkpoint__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_clog__checkpoint__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_CLOG_CHECKPOINT_START(arg1) \
DTRACE_PROBE1 (postgresql, clog__checkpoint__start, arg1)

/* TRACE_POSTGRESQL_CLOG_CHECKPOINT_DONE ( char ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_CLOG_CHECKPOINT_DONE_ENABLED() __builtin_expect (clog__checkpoint__done_semaphore, 0)
#define postgresql_clog__checkpoint__done_semaphore clog__checkpoint__done_semaphore
#else
#define TRACE_POSTGRESQL_CLOG_CHECKPOINT_DONE_ENABLED() __builtin_expect (postgresql_clog__checkpoint__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_clog__checkpoint__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_CLOG_CHECKPOINT_DONE(arg1) \
DTRACE_PROBE1 (postgresql, clog__checkpoint__done, arg1)

/* TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_START ( char ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_START_ENABLED() __builtin_expect (subtrans__checkpoint__start_semaphore, 0)
#define postgresql_subtrans__checkpoint__start_semaphore subtrans__checkpoint__start_semaphore
#else
#define TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_START_ENABLED() __builtin_expect (postgresql_subtrans__checkpoint__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_subtrans__checkpoint__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_START(arg1) \
DTRACE_PROBE1 (postgresql, subtrans__checkpoint__start, arg1)

/* TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_DONE ( char ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_DONE_ENABLED() __builtin_expect (subtrans__checkpoint__done_semaphore, 0)
#define postgresql_subtrans__checkpoint__done_semaphore subtrans__checkpoint__done_semaphore
#else
#define TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_DONE_ENABLED() __builtin_expect (postgresql_subtrans__checkpoint__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_subtrans__checkpoint__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_DONE(arg1) \
DTRACE_PROBE1 (postgresql, subtrans__checkpoint__done, arg1)

/* TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_START ( char ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_START_ENABLED() __builtin_expect (multixact__checkpoint__start_semaphore, 0)
#define postgresql_multixact__checkpoint__start_semaphore multixact__checkpoint__start_semaphore
#else
#define TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_START_ENABLED() __builtin_expect (postgresql_multixact__checkpoint__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_multixact__checkpoint__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_START(arg1) \
DTRACE_PROBE1 (postgresql, multixact__checkpoint__start, arg1)

/* TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_DONE ( char ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_DONE_ENABLED() __builtin_expect (multixact__checkpoint__done_semaphore, 0)
#define postgresql_multixact__checkpoint__done_semaphore multixact__checkpoint__done_semaphore
#else
#define TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_DONE_ENABLED() __builtin_expect (postgresql_multixact__checkpoint__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_multixact__checkpoint__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_DONE(arg1) \
DTRACE_PROBE1 (postgresql, multixact__checkpoint__done, arg1)

/* TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_START ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_START_ENABLED() __builtin_expect (twophase__checkpoint__start_semaphore, 0)
#define postgresql_twophase__checkpoint__start_semaphore twophase__checkpoint__start_semaphore
#else
#define TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_START_ENABLED() __builtin_expect (postgresql_twophase__checkpoint__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_twophase__checkpoint__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_START() \
DTRACE_PROBE (postgresql, twophase__checkpoint__start)

/* TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_DONE ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_DONE_ENABLED() __builtin_expect (twophase__checkpoint__done_semaphore, 0)
#define postgresql_twophase__checkpoint__done_semaphore twophase__checkpoint__done_semaphore
#else
#define TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_DONE_ENABLED() __builtin_expect (postgresql_twophase__checkpoint__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_twophase__checkpoint__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_DONE() \
DTRACE_PROBE (postgresql, twophase__checkpoint__done)

/* TRACE_POSTGRESQL_SMGR_MD_READ_START ( int, unsigned int, unsigned int, unsigned int, unsigned int, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_SMGR_MD_READ_START_ENABLED() __builtin_expect (smgr__md__read__start_semaphore, 0)
#define postgresql_smgr__md__read__start_semaphore smgr__md__read__start_semaphore
#else
#define TRACE_POSTGRESQL_SMGR_MD_READ_START_ENABLED() __builtin_expect (postgresql_smgr__md__read__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_smgr__md__read__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_SMGR_MD_READ_START(arg1, arg2, arg3, arg4, arg5, arg6) \
DTRACE_PROBE6 (postgresql, smgr__md__read__start, arg1, arg2, arg3, arg4, arg5, arg6)

/* TRACE_POSTGRESQL_SMGR_MD_READ_DONE ( int, unsigned int, unsigned int, unsigned int, unsigned int, int, int, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_SMGR_MD_READ_DONE_ENABLED() __builtin_expect (smgr__md__read__done_semaphore, 0)
#define postgresql_smgr__md__read__done_semaphore smgr__md__read__done_semaphore
#else
#define TRACE_POSTGRESQL_SMGR_MD_READ_DONE_ENABLED() __builtin_expect (postgresql_smgr__md__read__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_smgr__md__read__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_SMGR_MD_READ_DONE(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) \
DTRACE_PROBE8 (postgresql, smgr__md__read__done, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)

/* TRACE_POSTGRESQL_SMGR_MD_WRITE_START ( int, unsigned int, unsigned int, unsigned int, unsigned int, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_SMGR_MD_WRITE_START_ENABLED() __builtin_expect (smgr__md__write__start_semaphore, 0)
#define postgresql_smgr__md__write__start_semaphore smgr__md__write__start_semaphore
#else
#define TRACE_POSTGRESQL_SMGR_MD_WRITE_START_ENABLED() __builtin_expect (postgresql_smgr__md__write__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_smgr__md__write__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_SMGR_MD_WRITE_START(arg1, arg2, arg3, arg4, arg5, arg6) \
DTRACE_PROBE6 (postgresql, smgr__md__write__start, arg1, arg2, arg3, arg4, arg5, arg6)

/* TRACE_POSTGRESQL_SMGR_MD_WRITE_DONE ( int, unsigned int, unsigned int, unsigned int, unsigned int, int, int, int ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_SMGR_MD_WRITE_DONE_ENABLED() __builtin_expect (smgr__md__write__done_semaphore, 0)
#define postgresql_smgr__md__write__done_semaphore smgr__md__write__done_semaphore
#else
#define TRACE_POSTGRESQL_SMGR_MD_WRITE_DONE_ENABLED() __builtin_expect (postgresql_smgr__md__write__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_smgr__md__write__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_SMGR_MD_WRITE_DONE(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) \
DTRACE_PROBE8 (postgresql, smgr__md__write__done, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)

/* TRACE_POSTGRESQL_WAL_INSERT ( unsigned char, unsigned char ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_WAL_INSERT_ENABLED() __builtin_expect (wal__insert_semaphore, 0)
#define postgresql_wal__insert_semaphore wal__insert_semaphore
#else
#define TRACE_POSTGRESQL_WAL_INSERT_ENABLED() __builtin_expect (postgresql_wal__insert_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_wal__insert_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_WAL_INSERT(arg1, arg2) \
DTRACE_PROBE2 (postgresql, wal__insert, arg1, arg2)

/* TRACE_POSTGRESQL_WAL_SWITCH ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_WAL_SWITCH_ENABLED() __builtin_expect (wal__switch_semaphore, 0)
#define postgresql_wal__switch_semaphore wal__switch_semaphore
#else
#define TRACE_POSTGRESQL_WAL_SWITCH_ENABLED() __builtin_expect (postgresql_wal__switch_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_wal__switch_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_WAL_SWITCH() \
DTRACE_PROBE (postgresql, wal__switch)

/* TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_START ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_START_ENABLED() __builtin_expect (wal__buffer__write__dirty__start_semaphore, 0)
#define postgresql_wal__buffer__write__dirty__start_semaphore wal__buffer__write__dirty__start_semaphore
#else
#define TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_START_ENABLED() __builtin_expect (postgresql_wal__buffer__write__dirty__start_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_wal__buffer__write__dirty__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_START() \
DTRACE_PROBE (postgresql, wal__buffer__write__dirty__start)

/* TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_DONE ( ) */
#if defined STAP_SDT_V1
#define TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_DONE_ENABLED() __builtin_expect (wal__buffer__write__dirty__done_semaphore, 0)
#define postgresql_wal__buffer__write__dirty__done_semaphore wal__buffer__write__dirty__done_semaphore
#else
#define TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_DONE_ENABLED() __builtin_expect (postgresql_wal__buffer__write__dirty__done_semaphore, 0)
#endif
__extension__ extern unsigned short postgresql_wal__buffer__write__dirty__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_DONE() \
DTRACE_PROBE (postgresql, wal__buffer__write__dirty__done)

